### ISSUE TITLE
lspformat 

### ISSUE THREAD

**Issue by bogre** [fitrh/init.nvim#2]
Hi,
just in case, if it is not fixed or if I didn't miss something,
i've noticed that 
lua/config/lsp/command/buffer.lua line 19 should be like this
`lsp.formatting({ bufnr = bufnr, timeout_ms = timeout })`
so, lsp.formatting instead lsp.format

**Comment by fitrh** [comment]
I'm sorry, I forgot to mention it in the README, this configuration uses neovim nightly, so most of the features are based on the nightly release.

Related commit: 0a4e171
Neovim PR: https://github.com/neovim/neovim/pull/18193

**Comment by bogre** [comment]
aa, I see, anyway, thank you for response. I suppose this one should be closed then.
