### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by thieung** [fitrh/init.nvim#3]
Thanks for your cool config.

I tried to clone your config into my machine and start to setup but can not. It thrown these errors:
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/79964592/184672055-537371c9-9bb0-42ff-bdf3-9a087a41449e.png">

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/79964592/184672365-3b93c6d2-53b2-4b9c-8a56-6fdc2cb98c07.png">

Could you please help me to add some guides to install this cool config?

Thanks so much!

**Comment by fitrh** [comment]
> Could you please help me to add some guides to install this cool config?

Sorry for the inconvenience, I always want to provide an installation guide but hasn't had some free time to do so.

It seems you are not using the nightly version of neovim, I'm following the nightly build on weekly basis, your error will occur since https://github.com/fitrh/init.nvim/commit/91d3eead1e2cf6f960012343e2ee6edf172624ef (a follow-up of this https://github.com/neovim/neovim/pull/19238).

Until I can provide a proper installation guide, when you have any issues with this configuration, feel free to ask here.

**Comment by fitrh** [comment]
You can use the following snippets

```sh
#!/usr/bin/env sh

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"

cp "$CONFIG/init.lua.example" "$CONFIG/init.lua" &&
    rm -rf "$CONFIG/plugin/packer_compiled.lua" &&
    nvim --headless \
        -c 'autocmd User PackerComplete quitall' \
        -c 'lua require("config.plugin.packer")' \
        -c 'PackerSync'

```

You can remove the `--headless` flag if you want to see the progress, just make sure that you have packer and nvim-treesitter requirements

**Comment by thieung** [comment]
Thanks @fitrh, I tried with latest nightly version and it's solved.
I'm trying to understand your config and use it as reference for my own <3
Thanks so much!

**Comment by sanihaq** [comment]
I'm getting this error

> Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: .../nvim/lua/config/plugin/colorscheme/tokyonight/setup.lua:20: module 'tokyonight' not found:
        no field package.preload['tokyonight']
        no file './tokyonight.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/tokyonight.lua'
        no file '/usr/local/share/lua/5.1/tokyonight.lua'
        no file '/usr/local/share/lua/5.1/tokyonight/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/tokyonight.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/tokyonight/init.lua'
        no file './tokyonight.so'
        no file '/usr/local/lib/lua/5.1/tokyonight.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/tokyonight.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        .../nvim/lua/config/plugin/colorscheme/tokyonight/setup.lua:20: in main chunk
        [C]: in function 'require'
        /home/sani/.config/nvim/after/plugin/colorscheme.lua:18: in function </home/sani/.config/nvim/after/plugin/colorscheme.lua:3>

Can you help? Thanks.
