### ISSUE TITLE
Install guide for beginners

### ISSUE THREAD

**Issue by sanihaq** [fitrh/init.nvim#8]
Please add at least a basic guide, so beginners can get up and running quickly.

**Comment by sanihaq** [comment]
I'm getting this error

> Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: .../nvim/lua/config/plugin/colorscheme/tokyonight/setup.lua:20: module 'tokyonight' not found:
        no field package.preload['tokyonight']
        no file './tokyonight.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/tokyonight.lua'
        no file '/usr/local/share/lua/5.1/tokyonight.lua'
        no file '/usr/local/share/lua/5.1/tokyonight/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/tokyonight.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/tokyonight/init.lua'
        no file './tokyonight.so'
        no file '/usr/local/lib/lua/5.1/tokyonight.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/tokyonight.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        .../nvim/lua/config/plugin/colorscheme/tokyonight/setup.lua:20: in main chunk
        [C]: in function 'require'
        /home/sani/.config/nvim/after/plugin/colorscheme.lua:18: in function </home/sani/.config/nvim/after/plugin/colorscheme.lua:3>

@fitrh  Can you help? Thanks.

**Comment by fitrh** [comment]
> Please add at least a basic guide, so beginners can get up and running quickly.

Sorry for the inconvenience, I have a setup script in my local machine but hasn't
had some free time to tested it

You can try this script

```sh
sh#!/usr/bin/env sh

main() (
    CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"

    cp "$CONFIG/init.lua.example" "$CONFIG/init.lua"
    rm -rf "$CONFIG/plugin/packer_compiled.lua"

    case "$1" in
        "headless")
            nvim --headless \
                -u NONE \
                -c 'autocmd User PackerComplete quitall' \
                -c 'lua require("config.plugin.packer")' \
                -c 'PackerSync'
            ;;
        *)
            nvim \
                -u NONE \
                -c 'set cmdheight=1' \
                -c 'lua require("config.plugin.packer")' \
                -c 'PackerSync'
            ;;
    esac

)

main "$@"
```

- Save it as `setup.sh`
- Set it as executable with `chmod u+x setup.sh`
- Run with `./setup.sh` or `./setup.sh headless`

**Comment by sanihaq** [comment]
@fitrh thank you. It worked. Please add it to readme.  It would be very helpful to know your workflow, please consider writing a blog post or in readme about it.
